import Head from "next/head";
import Navbar from "../componenets/navbar";
import styles from "../styles/Home.module.css";
// import Contact from "./Contact";
import HomePageContent from "../componenets/homePageContent";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePageContent />
    </div>
  );
}
